//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 11:38:16 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.bank.com/account", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_bank_com.account;
